channels:
  - conda-forge
dependencies:
  # core deps
  - python=3.9
  - pydantic =1.8
  - backoff
  - yq
  - schedule
  - requests
  - requests-toolbelt
  - pymongo
  - psutil
  - slackclient
  - ujson
  - python-xxhash
  - nest-asyncio
  - pycryptodome
  - aiohttp
  
  # ampel-plotting
  - matplotlib-base
  
  # ampel-ztf
  - python-confluent-kafka
  - fastavro

  # astro deps
  - sncosmo
  - iminuit
  - astroquery
  - pandas

  # dev deps
  - mypy ==0.910
  - types-requests
  - types-pytz
  - pytest
  - pytest-mock
  - pytest-cov

  # things missing or stale on conda-forge
  - pip:
    - ampel-ztf = 0.8.0a4
    - pymage @ https://github.com/MickaelRigault/pymage/archive/v1.0.tar.gz#sha256=11e99c4ea06b76ca7fb5b42d1d35d64139a4fa6f7f163a2f0f9cc3ea0b3c55eb
    - sfdmap
